[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.16"
optimizer = true
optimizer_runs = 200
no_match_coverage = "(script|test|mocks)"
fs_permissions = [
    { access = "read", path = "./out/" },
    { access = "read", path = "./script/input/" },
    { access = "read-write", path = "./script/output/" }
]

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
